### PR TITLE
Compile sdk

### LINKED ISSUE #59: Generated SDK does not compile
To make testing and using the generated SDK easier, source2gen could

- (1) Add dummies for missing types that aren't registered in the schema system, e.g. `CHandle`, `CUtlVector`, and many more.
- (1) Add a dummy `interfaces` namespace used to access static fields
- -(2) Take into account template arguments when sorting class definitions- we're no longer sorting types
- Fully qualify template argument names and include required modules (Assumes #58 is merged)
- Translate built-in template argument names to C++ types, e.g. `CUtlVector<int32>` -> `CUtlVector<std::int32_t>`
- Don't forward declare nested types, because that doesn't work in C++
- Rename nested types to use underscores
- Generate `static_assert`ions to make sure the generated types have the layout we expected
- Use large integer types for consecutive bitfields with entries crossing byte borders (e.g. `char a: 7; char b: 2`)
- Detect misaligned fields and types and replace them with dummies
- Replace template types with non-type template parameters with dummies (e.g. `CUtlLeanVectorFixedGrowable`) (because those parameters are not included in the sdk)

This list grows as more issues surface

(1) The user can replace the dummies with real implementations if they want to access the affected types.  To compile the SDK, dummies are enough  
(2) This requires an update to the ordering algorithm to detect indirect cyclic dependencies, e.g. player->entity->world->player

### PR DESCRIPTION
**Pull request by Cre3per**
Closes #59  
Depends on #58

- The generated SDK can be compiled without changes (CMake)
- The generated SDK contains `static_assert`ions for type sizes and field offsets where possible, which pass (Tested with CS2 9035763 on Linux)

Additionally, for testing purposes, I added a conan recipe to the SDK. The generated conan package works, but there are some properties we should set dynamically. There's a TODO in the recipe and conan isn't advertised in the README, so we can do it that a follow-up issue.

### CODE REVIEW

**Comment by Cre3per** [comment]
Marked as draft until #58 is merged.

There is 1 open TOOD comment (not a typo) that is already being considered by @es3n1n, thanks buddy!

This branch is otherwise complete and ready to use, I have not planned any further changes.

**Comment by Redict** [comment]
@es3n1n merge?

**Comment by es3n1n** [comment]
> @es3n1n merge?

Hi, there is still some work that we have to do first before merging. I will take a look at it next week hopefully 🫣

**Comment by es3n1n** [comment]
Tweaked a few things, add some missing types and now it works as expected on my machine too.
Tested with:
- MSVC 19.37.32824
- clang 18 (windows)
- clang 17 (linux)
- gcc 11.4.0

Looks like we're good to go.

**Review by es3n1n — APPROVED** [review]

**Review by cpz — APPROVED** [review]

**Comment by es3n1n** [comment]
yay

**Pull request merged**
